"""Building on the concept of Hawkes processes, which capture self-exciting behavior in market orders, this factor seeks to exploit the momentum generated by sustained order flow. When significant buy or sell orders cluster, they are likely to influence future price movements, creating momentum that can be captured by this signal."""

from __future__ import annotations

import pandas as pd
import numpy as np

from quant_fund_agent.factors.base import BaseFactor
from quant_fund_agent.factors.registry import register_factor
from quant_fund_agent.factors.ops import ts_sum, adv

@register_factor
class HawkesOrderFlowMomentum(BaseFactor):
    factor_id = "hawkes_order_flow_momentum"
    name = "Hawkes Order Flow Momentum"
    category = "momentum"
    description = ("This factor computes the cumulative order flow (buy minus sell volume) over a specified look-back period and normalizes it by the total volume. A higher value indicates strong directional momentum driven by order flow, while a lower value suggests weak or reversing momentum.")
    inputs = ["volume"]

    def calc(self, data: dict[str, pd.DataFrame]) -> pd.DataFrame:
        volume = data["volume"].fillna(0.0)
        buy_volume = volume.where(volume > 0, 0)
        sell_volume = volume.where(volume < 0, 0)
        cumulative_order_flow = ts_sum(buy_volume, 5) + ts_sum(sell_volume, 5)
        total_volume = adv(volume, 5)
        momentum_signal = cumulative_order_flow / total_volume.replace(0, np.nan)
        return momentum_signal