"""In markets characterized by heavy-tailed distributions, unusual spikes in volume can signal significant price movements ahead. This factor leverages the momentum generated by high-volume trading days, which often precede directional trends, as suggested by the implications of heavy-tailed queueing theory. Thus, high volume in conjunction with price momentum can indicate strong forthcoming price action."""

from __future__ import annotations

import pandas as pd
import numpy as np

from quant_fund_agent.factors.base import BaseFactor
from quant_fund_agent.factors.ops import (adv, delta, ts_mean, sign, ts_rank)
from quant_fund_agent.factors.registry import register_factor


@register_factor
class HeavyTailedVolumeMomentum(BaseFactor):
    factor_id = "heavy_tailed_volume_momentum"
    name = "Heavy-Tailed Volume Momentum"
    category = "momentum"
    description = ("This signal computes the ratio of current bar volume to an exponentially weighted moving average of previous volumes, "
                   "adjusted for recent price momentum, indicating potential breakout or breakdown conditions.")
    inputs = ["volume", "close"]

    def calc(self, data: dict[str, pd.DataFrame]) -> pd.DataFrame:
        volume = data["volume"].fillna(0.0)
        close = data["close"].fillna(0.0)
        adv_volume = adv(volume, 20)
        current_volume = volume
        momentum = delta(close, 1)
        momentum_adjusted = momentum.where(momentum > 0, 0.0)
        signal = current_volume / adv_volume * ts_rank(momentum_adjusted, 20)
        return signal