"""Drawing from the principles of self-exciting processes, this factor captures the momentum generated by volume spikes in a stock. Increased trading activity often precedes price movements, as seen in self-exciting models, indicating that higher volume can lead to continued price momentum in the same direction."""

from __future__ import annotations

import pandas as pd
import numpy as np

from quant_fund_agent.factors.base import BaseFactor
from quant_fund_agent.factors.ops import (correlation, adv, ts_sum, ts_mean)
from quant_fund_agent.factors.registry import register_factor


@register_factor
class SelfExcitingVolumeMomentum(BaseFactor):
    factor_id = "self_exciting_volume_momentum"
    name = "Self-Exciting Volume Momentum"
    category = "momentum"
    description = ("This signal computes the correlation between recent volume spikes and subsequent price movements, identifying stocks where high trading volume leads to continued price momentum.")
    inputs = ["close", "volume"]

    def calc(self, data: dict[str, pd.DataFrame]) -> pd.DataFrame:
        close = data["close"].fillna(0.0)
        volume = data["volume"].fillna(0.0)
        adv_volume = adv(volume, 20)
        recent_volume_spike = volume - adv_volume
        correlation_signal = correlation(recent_volume_spike, close.pct_change(), 5)
        return correlation_signal