"""A directional move generated by unusually high signed-volume pressure but followed by rapid normalization in activity can leave dealers with unwanted inventory even after the initiating flow has stopped. Estimate the portion of recent price displacement not explained by the persistent component of a causal signed-flow propagator; fade this residual when current volume has fallen below its local baseline and the close is no longer at the directional range extreme. The other side is liquidity providers unwinding inventory and short-horizon arbitrageurs; the mechanism is rejected if low-activity post-burst displacements retain their sign rather than reverting over the next six sessions."""

from __future__ import annotations

import numpy as np
import pandas as pd

from quant_fund_agent.factors.base import BaseFactor
from quant_fund_agent.factors.ops import rank
from quant_fund_agent.factors.registry import register_factor


def _causal_propagator_gap(
    ret: pd.DataFrame,
    slow_flow: pd.DataFrame,
) -> pd.DataFrame:
    """Estimate trailing slow-flow impact and return its unexplained displacement."""
    displacement = ret.rolling(5, min_periods=3).sum()
    covariance = displacement.rolling(40, min_periods=20).cov(slow_flow)
    flow_variance = slow_flow.rolling(40, min_periods=20).var()
    impact_beta = (covariance / flow_variance.replace(0.0, np.nan)).clip(-10.0, 10.0)
    return displacement - impact_beta * slow_flow


@register_factor
class TransientInventoryRestockingImpactGapV2(BaseFactor):
    """Fade low-activity residual displacement after a signed-flow burst."""

    factor_id = "transient_inventory_restocking_impact_gap_v2"
    name = "Transient Inventory Restocking Impact Gap"
    category = "microstructure"
    description = (
        "Uses close-location value times relative volume as a signed-flow proxy, "
        "compares realized displacement with a causally calibrated slow-flow "
        "propagator, and fades residual moves only after activity and range "
        "extremity have normalized."
    )
    window_length = 60
    inputs = ["close", "high", "low", "volume"]
    prediction_horizon = 6
    suggested_horizons = [6]

    def calc(self, data: dict[str, pd.DataFrame]) -> pd.DataFrame:
        close = data["close"].astype(float)
        high = data["high"].astype(float)
        low = data["low"].astype(float)
        volume = data["volume"].astype(float).fillna(0.0).clip(lower=0.0)

        prior_close = close.shift(1).replace(0.0, np.nan)
        ret = (close / prior_close - 1.0).replace([np.inf, -np.inf], np.nan).fillna(0.0)

        price_range = (high - low).replace(0.0, np.nan)
        close_location = (
            (2.0 * close - high - low) / price_range
        ).replace([np.inf, -np.inf], np.nan).clip(-1.0, 1.0).fillna(0.0)

        volume_baseline = volume.ewm(
            halflife=20, adjust=False, min_periods=5
        ).mean().replace(0.0, np.nan)
        relative_volume = (volume / volume_baseline).clip(0.0, 5.0)
        signed_flow = (close_location * relative_volume).fillna(0.0)

        fast_flow = signed_flow.ewm(
            halflife=2, adjust=False, min_periods=3
        ).mean()
        slow_flow = signed_flow.ewm(
            halflife=12, adjust=False, min_periods=8
        ).mean()
        transient_flow = fast_flow - slow_flow

        gap = _causal_propagator_gap(ret, slow_flow)
        displacement_scale = (
            ret.rolling(20, min_periods=10).std() * np.sqrt(5.0)
        ).replace(0.0, np.nan)
        standardized_gap = gap / displacement_scale

        burst_scale = transient_flow.rolling(30, min_periods=15).std().replace(0.0, np.nan)
        burst_z = transient_flow / burst_scale
        burst_strength = np.tanh((burst_z.abs() - 0.5).clip(lower=0.0))

        activity_decay = (1.0 - relative_volume).clip(0.0, 1.0)
        location_relaxation = (1.0 - close_location.abs()).clip(0.0, 1.0)
        directional_alignment = (gap * fast_flow > 0.0).astype(float)

        restocking_gate = (
            activity_decay
            * location_relaxation
            * burst_strength
            * directional_alignment
        )
        contrarian_score = (-standardized_gap * restocking_gate).replace(
            [np.inf, -np.inf], np.nan
        )

        eligible_score = contrarian_score.where(restocking_gate > 0.0)
        return (rank(eligible_score) - 0.5).fillna(0.0)
